name: szu-mnsr-opt

channels:
  - conda-forge

dependencies:
  - python=3.13
  - openmc=0.15.3
  - numpy=2.4.6
  - pandas=3.0.3
  - matplotlib=3.10.9
  - h5py=3.16.0
  - pillow=12.2.0
  - ipython=9.14.1
  - ipykernel=7.3.0
